### ISSUE TITLE
FloatBuffer error

### ISSUE THREAD

**Issue by iamdipankarj** [lmdbjava/lmdbjava#136]
java -jar target/lwjgl3-demos.jar
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.FloatBuffer.clear()Ljava/nio/FloatBuffer;
        at org.lwjgl.demo.opengl.UniformArrayDemo.<init>(UniformArrayDemo.java:47)
        at org.lwjgl.demo.opengl.UniformArrayDemo.main(UniformArrayDemo.java:291)

**Comment by benalexau** [comment]
This is the LmdbJava project. Your stack trace is from the [LWJGL](https://www.lwjgl.org/).
