### ISSUE TITLE
ExceptionInInitializerError on Env.create()

### ISSUE THREAD

**Issue by Crashcrafter** [lmdbjava/lmdbjava#182]
I just started using lmdbjava and wanted to test the library, but calling Env.create() (no matter what follows like setMapSize etc.) just throws an Exception. I also just copy-pasted the code from TutorialTest.java, but it does not work.

I am using version 0.8.1 of lmdbjava.
```gradle
implementation("org.lmdbjava:lmdbjava:0.8.1")
```
Gradle: 7.2
Java: 16
Kotlin: 1.5.30 (which shouldn't matter at all)

Here is my code:
```kt
Env.create().setMapSize(10_485_760).setMaxReaders(10).setMaxDbs(4).open(dirFile)
```
And here the Exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lmdbjava.ByteBufferProxy.<clinit>(ByteBufferProxy.java:71)
	at org.lmdbjava.Env.create(Env.java:92)
	at dev.crash.storage.FunctionsKt.simpleEnv(Functions.kt:11)
	at dev.crash.storage.BlockTrie.addBlock(BlockTrie.kt:16)
	at dev.crash.node.Mempool.calculateBlock(Mempool.kt:28)
	at dev.crash.node.KotlinNode.start(KotlinNode.kt:19)
	at dev.crash.node.KotlinNode$start$1.invokeSuspend(KotlinNode.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:167)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:408)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:442)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeUndispatched(CancellableContinuationImpl.kt:529)
	at kotlinx.coroutines.EventLoopImplBase$DelayedResumeTask.run(EventLoop.common.kt:497)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @cad498c
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
	at org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy.findField(ByteBufferProxy.java:163)
	at org.lmdbjava.ByteBufferProxy$ReflectiveProxy.<clinit>(ByteBufferProxy.java:222)
	... 18 more

```

**Comment by Geruls** [comment]
this is probably because you're trying to run the code in Kotlin. I don't think Kotlin has any system supporting Java modules.

**Comment by benalexau** [comment]
Have you tried launching the JVM with `--add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED`?

**Comment by code-hunger** [comment]
I got the same error using Java 17. Switching to Java 11 I get the following warning: 

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy (file:/home/alex/.m2/repository/com/github/lmdbjava/lmdbjava/lmdbjava-0.8.2/lmdbjava-lmdbjava-0.8.2.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of org.lmdbjava.ByteBufferProxy$AbstractByteBufferProxy
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Sad to see it :(

**Comment by benalexau** [comment]
Closing this in favor of tracking changes required to accommodate newer Java versions in #42.
