### ISSUE TITLE
Regression - Env.create gives Dbi$BadValueSizeException

### ISSUE THREAD

**Issue by kamstrup** [lmdbjava/lmdbjava#21]
My code that worked in 0.0.1 is broken under 0.0.2 and 0.0.3. Giving the following exception:

```
org.lmdbjava.Dbi$BadValueSizeException: Unsupported size of key/DB name/data, or wrong DUPFIXED size (-30781)

	at org.lmdbjava.ResultCodeMapper.<clinit>(ResultCodeMapper.java:56)
	at org.lmdbjava.Env$Builder.open(Env.java:369)
	at org.lmdbjava.Env$Builder.open(Env.java:393)
	at com.unsilo.conceptstore.LmdbConceptStoreConnector.<init>(LmdbConceptStoreConnector.java:59)
	at com.unsilo.conceptstore.LmdbConceptStoreConnector.<init>(LmdbConceptStoreConnector.java:68)
	at com.unsilo.conceptstore.ConceptStoreConnector.lookup(ConceptStoreConnector.java:17)
	at com.unsilo.conceptstore.ConceptStoreConnectorTest.foo(ConceptStoreConnectorTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
My (working) 0.0.1 code looks like:
```java
        env = Env.create()
                .setMapSize(256, ByteUnit.MEBIBYTES)
                .setMaxDbs(32)
                .open(file, 0664,
                        EnvFlags.MDB_NOSYNC,
                        EnvFlags.MDB_WRITEMAP,
                        EnvFlags.MDB_MAPASYNC);
```

And for 0.0.3, where I get the error:
```java
        env = Env.create()
                .setMapSize(MEBIBYTES.toBytes(256))
                .setMaxDbs(32)
                .open(file, 0664,
                        EnvFlags.MDB_NOSYNC,
                        EnvFlags.MDB_WRITEMAP,
                        EnvFlags.MDB_MAPASYNC);
```
I also tried setting maxDbs to 1 and omitting the file mode and envflags, but get the same result

**Comment by benalexau** [comment]
Which OS is this on? There is an issue with the byte size sent through to the C side on Windows (see #18). Can you try the 0.0.4-SNAPSHOT?

**Comment by kamstrup** [comment]
0.0.4-SNAPSHOT gives almost exactly the same error:
```
org.lmdbjava.Dbi$BadValueSizeException: Unsupported size of key/DB name/data, or wrong DUPFIXED size (-30781)

	at org.lmdbjava.ResultCodeMapper.<clinit>(ResultCodeMapper.java:56)
	at org.lmdbjava.Env$Builder.open(Env.java:369)
	at com.unsilo.conceptstore.LmdbConceptStoreConnector.<init>(LmdbConceptStoreConnector.java:58)
       ... more frames from my code
```

I am running Ubuntu 16.04 with Oracle's jvm 1.8.0_65.

**Comment by benalexau** [comment]
Is this a new database file? I just added the following method to our `EnvTest` class and it worked fine on Arch Linux (64-bit) against LmdbJava master:

```
  @Test
  public void issue21() throws IOException {
    final File file = tmp.newFolder();
    System.out.println("Size is " + MEBIBYTES.toBytes(256));  // reports 268435456
    Env<ByteBuffer> env = Env.create()
        .setMapSize(MEBIBYTES.toBytes(256))
        .setMaxDbs(32)
        .open(file, 0664,
              EnvFlags.MDB_NOSYNC,
              EnvFlags.MDB_WRITEMAP,
              EnvFlags.MDB_MAPASYNC);
  }
```

Does the `TutorialTest` work on your machine (could you try copying the tutorial and executing it)? Do you receive the sane byte size (are you using `com.jakewharton.byteunits:byteunits:0.9.1`)?

**Comment by kamstrup** [comment]
Tested the TutorialTest code and it runs fine. As a last ditch effort I commented out all of my own code and added line-by-line until I got the error. Turns out that org.lmdbjava.Env$Builder.open() is not the method throwing the exception at all! (??). The real culprit is a DBi.get() call. I guess something corrupts the stacktrace... Digging a bit more

**Comment by kamstrup** [comment]
It turns out the was a missing .flip() on my key buffer for that dbi.get() call... Wondering how this worked before... Still haven't figured out why the stacktrace points at Env.open() and not dbi.get()

**Comment by phraktle** [comment]
I also had some cases with lmdbjava previously where I've seen pink elephants (an exception with the wrong stack trace, where there was other code executed later down the line). I'm guessing this is due to some mis-managed allocations or other corruption... Do you have a reproducible test case where this happens?

**Comment by benalexau** [comment]
> Still haven't figured out why the stacktrace points at Env.open() and not dbi.get()

I've also seen C-side error values corrupting the stack trace a few times before.

> It turns out the was a missing .flip() on my key buffer for that dbi.get() call.

Glad you found it! 

We did some buffer changes in commit 6150c42dca32ff36b4c2f51189a663df0e7d5506, which changed from storing the full buffer capacity to just the limit. That's why it would have worked previously.

I also had a very similar bug in the benchmark project, fixed in commit https://github.com/lmdbjava/benchmarks/commit/4a01fda4c4c2b55e40bf5e8daa15ef182f2ada1e. 

I'm guessing we can close this ticket?

**Comment by kamstrup** [comment]
Yep. Seems all clear to me now :-)

Thanks for the awesome project - hope I can contribute something more tangible later! ;-)

**Comment by kamstrup** [comment]
@phraktle Just a Dbi<ByteBuffer> created with MDB_INTEGERKEY, and then passing a ByteBuffer buf = allocateDirect(4) where you did buf.putInt(), but NOT flip() to dbi.get() causes it for me on 0.0.2, 0.0.3, and 0.0.4-SNAPSHOT

**Comment by benalexau** [comment]
I just added some tests and fixes to automatically detected illegal zero byte buffers in the situations they are prohibited, as per the http://lmdb.tech/doc/group__mdb.html#structMDB__val docs:

> Key sizes must be between 1 and mdb_env_get_maxkeysize() inclusive. The same applies to data sizes in databases with the MDB_DUPSORT flag. Other data items can in theory be from 0 to 0xffffffff bytes long. 

Hopefully this will save others from similar confusing errors.

**Comment by kamstrup** [comment]
:+1:

**Comment by Longyinyun** [comment]
I also encountered the same problem today. It's due to the buffer.flip().  Thanks bro! :)
