### ISSUE TITLE
Having issues allocating a reasonable map size on Windows

### ISSUE THREAD

**Issue by HenrikJohnson** [lmdbjava/lmdbjava#221]
I am running the following code on Linux and it works fine on Linux but fails on Windows (64 bit). 

```
        final long MAP_SIZE = 256L * 1024 * 1024 * 1024
        return Env.create()
                .setMapSize(MAP_SIZE)
                .setMaxDbs(30)
                .setMaxReaders(10)
                .open(path, MDB_WRITEMAP, MDB_NOTLS);
```

The code does work fine when I run it on Linux with the same parameters. On Windows I get the following exception.

```
    Platform constant error code: EINPROGRESS Unknown error (112)
    org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: EINPROGRESS Unknown error (112)
	at app//org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
	at app//org.lmdbjava.Env$Builder.open(Env.java:530)
	at app//org.lmdbjava.Env$Builder.open(Env.java:547)
	at app//LmdbTest.createDb(LmdbMetadataRepositoryStorage.java:438)
```

It comes back to life again if I change the map size to something very low such as 128MB. I am using Java17 (Corretto) and lmdbjava-0.83 and a current Windows 11 OS. For it to be feasible to use this library though I need to be able to store at least around 256GB of data in it.

**Comment by HenrikJohnson** [comment]
So I realized that this was because of the non sparse nature on Windows. Seems I was just out of disk space.
