### ISSUE TITLE
EINVAL 22 while deleting entries with a cursor

### ISSUE THREAD

**Issue by cdprete** [lmdbjava/lmdbjava#232]
Hi.

I'm using lmdbjava 0.8.3 and, from time to time, I get the following exception while iterating over a Dbi in order to delete all its entries:
```
org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: EINVAL Invalid argument (22)
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
        at org.lmdbjava.Cursor.delete(Cursor.java:124)
        at org.lmdbjava.CursorIterable$1.remove(CursorIterable.java:115)
```

The deletion logic is just:
```kotlin
val endKey = PriceKey.fromMdf2Price(price)
val lowerKey = readKeyLowerBound().populateWith(endKey.copy(sessionEndDate = EPOCH))
val upperKey = readKeyUpperBound().populateWith(endKey)
dbi.iterate(txWrite, closedOpen(lowerKey, upperKey)).use {
    val iterator = it.iterator()
    while(!closed.get() && iterator.hasNext()) {
         try {
             iterator.remove()
         } catch (ex: KeyNotFoundException) {
             logger.trace(ex.toString(), ex)
             break
         }
    }
}
```

Additional information:
- Env flags: MDB_NOSYNC, MDB_NORDAHEAD, MDB_NOSUBDIR
- I don't have nested write transactions

What could I check on my side to sort this out?

Also, it's to me weird and unexpected that I get a `KeyNotFoundException` if I'm iterating over a range.
If no key matches, I would expect the range to be empty and the iterator to be noop.

**Comment by cdprete** [comment]
After checking in details the code of the iterator, it seems like that `remove()` doesn't move the cursor.
As such, I've added a call to `next()` before calling `remove()` and this should solve the issue.
