### ISSUE TITLE
EIO Input/Output error (5)

### ISSUE THREAD

**Issue by cdprete** [lmdbjava/lmdbjava#233]
Hi.

I'm using lmdbjava 0.8.3 and, from time to time, I get the following exception while committing a write transaction:
```
org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: EIO Input/output error (5)
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
        at org.lmdbjava.Txn.commit(Txn.java:122)
```

The commit method is just:
```kotlin
private fun commit(force: Boolean = false) {
	if (txWrite == null) return
	val now = now()
	if(force || now >= (lastCommitTimestamp + config.commitInterval)) {
		logger.trace("Committing transaction")
		txWrite!!.commit()
		txWrite!!.close()
		txWrite = null
		env.sync(force)
		lastCommitTimestamp = now
	}
}
```

Does somebody have any idea on what that error is about and why may it happening?

Kind regards and thanks in advance for the support.

**Comment by at055612** [comment]
`EIO - a low-level I/O error occurred while writing.`

Could it be that the lmdb file has hit the per file limit for the filesystem, e.g. 4GB on FAT32?  Indicative of a hardware level issue I think.

**Comment by benalexau** [comment]
Probably best to ask on the LMDB mailing list if this remains an issue. 0.9.1-SNAPSHOT has a more recent version of LMDB embedded, so perhaps give it a try first.

**Comment by cdprete** [comment]
I didn't had this issue anymore in the meantime. 
Anyway, to ensure 100% compatibility (+ less overhead to have to extract the binaries from the at startup) I'm using LMDB that gets shipped with RedHat itself and make the library just point to it.

**Comment by benalexau** [comment]
Glad you sorted it out, albeit it unless RedHat is compiling LMDB with non-default flags I can't see the difference from what our Zig build would have emitted.

**Comment by cdprete** [comment]
I was not implying that the RedHat version fixed it.
I just mentioned for completeness.

Il mar 18 feb 2025, 21:40 Ben Alex ***@***.***> ha scritto:
