### ISSUE TITLE
Apple Silicon M2: Platform constant error code: EINVAL Invalid argument (22) 

### ISSUE THREAD

**Issue by lfoppiano** [lmdbjava/lmdbjava#242]
Hi all, 
   I've been using LMDBJava for long time and since I switched to an Apple Silicon M2, now, I get the following error when opening the LMDB datastorage. 

```
org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: EINVAL Invalid argument (22)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
	at org.lmdbjava.Env$Builder.open(Env.java:585)
	at org.lmdbjava.Env$Builder.open(Env.java:606)
```

~~I suppose it's because the version 0.9.0 does not include the ARM compiled binary? Do you have any quick fix or solution, please?~~
There is support for Apple Silicon, I might be doing something wrong when I open the environment. 

Here my code, do you notice anything wrong? (the same code works on Linux): 

```java

        environment = Env.create()
                .setMapSize(1024L * 1024L * 1024L * 1024L)
                .setMaxReaders(configuration.getMaxAcceptedRequests())
                .setMaxDbs(10)
                .open(thePath, EnvFlags.MDB_NOTLS);

```

**Comment by neilyio** [comment]
I'm on Apple Silicon M1, I just started getting this issue today. I can read from the DB, but I cannot transact.

**Comment by benalexau** [comment]
I don't personally use Apple computers, so I cannot reproduce this. Perhaps give it a try with 0.9.1-SNAPSHOT which embeds a newer version of LMDB and see if that helps.

**Comment by benalexau** [comment]
Can someone with an Apple machine please try this with the 0.9.1 release (which was published last week) and comment here if it remains an issue?
