### ISSUE TITLE
Corrupted stacktraces

### ISSUE THREAD

**Issue by kamstrup** [lmdbjava/lmdbjava#25]
It has been observed many times that stacktraces from lmdbjava oftens ends up corrupted. See fx. here: https://github.com/lmdbjava/lmdbjava/issues/23, and here https://github.com/lmdbjava/lmdbjava/issues/21.

It also seems to end up pointing into org.lmdbjava.Env$Builder.open()... or maybe that's just for me.

**Comment by benalexau** [comment]
We've had two specific stack corruption scenarios to date:

* Issue #21: Attempting to store an `MDB_val` with a key length of zero
* Issue #23: Creation of two concurrent read transactions in the same thread

Both of these situations are no longer possible due to defensive checks subsequently added to LmdbJava.

It would of course be preferable that the root cause of stack corruption is identified, but there are at least five layers potentially contributing to it:

* End user code violating LMDB API contract
* LmdbJava
* JNR-FFF
* JVM
* LMDB native C library

I believe the easiest starting point would be develop C tests for the two error conditions we've encountered above against the [LMDB test harness](https://github.com/LMDB/lmdb) and compile these with [stack smashing detection](http://wiki.osdev.org/Stack_Smashing_Protector). At least this can demonstrate that LMDB itself doesn't corrupt the stack in those situations.

Another option would be changing JNR-FFF samples to deliberately cause buffer overruns and see if this corrupts the Java-side stack. But even if this happen, I don't know what prevention could be expected from JNR-FFF given the JVM operates in the same address space as the native library.

LmdbJava could add its own stack smashing protection-inspired canary values around memory addresses we're sending to the LMDB native side. We could check the canaries on the way back to determine if they've changed and throw a suitable exception (and hope the Java stack reflects it).

A further option would be to see if the same stack corruption is encountered when using LMDB via one of the other LMDB Java wrappers, such as [LmdbJNI](https://github.com/deephacks/lmdbjni/) or [LWJGL](https://github.com/LWJGL/lwjgl3/). The former uses HawtJNI and the latter uses javacpp, so at least there's some diversity across the JNI and Java abstraction layers.

We could also ask @hyc how LMDB would typically handle the situation where users invoke two read-only transactions in the same thread, and/or try to store a zero-sized key. Perhaps such API misuse (and it is misuse given the docs state not to do this) means the process memory may be corrupted.

If anyone has time to pursue any of the above suggestions or comments on how to best tackle this, please chime in...

**Comment by kamstrup** [comment]
I also got a corrupted trace yesterday because I tried writing something with a key len > 511. I suspect that it is pretty much all code that ends up mapping a native lmdb error code to a java exception that triggers this bug.

**Comment by phraktle** [comment]
Btw, this is not something that happens with `lmdbjni` under the same conditions. I suspect there's an issue somewhere in the native bindings.

**Comment by benalexau** [comment]
I'm very glad I posted the above ideas, as the two responses were absolutely invaluable for solving this!

The problem was the `ResultCodeMapper` created the exceptions (and stored them in a map) within the static initializer. At the time an LMDB error result code was presented, the mapped exception was simply returned. Therefore whichever code path happened to initialize `ResultCodeMapper` was reflected in the stack trace. This is why it was usually `Env.open(..)`, as reported elsewhere.

My initial idea to fix this was `Throwable.fillInStackTrace()`, however this wouldn't work if concurrent threads modified the same exception instance. It was therefore safer to just introduce a large `switch` statement, despite the unfortunate cyclomatic complexity this brings.

I verified the fix by commenting out the newly-added #26 `Txn` [guard statement line 246](https://github.com/lmdbjava/lmdbjava/commit/2697f3d8db95f7c166199797757e710edcdb5a14#diff-70c0292b645ac741245535c98a821e4cR241) and running the test again. The result is a correct stack trace:

```
Tests run: 22, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.034 sec <<< FAILURE! - in org.lmdbjava.TxnTest
largeKeysRejected(org.lmdbjava.TxnTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.lang.IndexOutOfBoundsException> but was<org.lmdbjava.Dbi$BadValueSizeException>
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: org.lmdbjava.Dbi$BadValueSizeException: Unsupported size of key/DB name/data, or wrong DUPFIXED size (-30781)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:72)
	at org.lmdbjava.Dbi.put(Dbi.java:306)
	at org.lmdbjava.Dbi.put(Dbi.java:275)
	at org.lmdbjava.TxnTest.largeKeysRejected(TxnTest.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 20 more
```

Thanks again to you guys for persevering with this issue. Apologies such a simple issue slipped through.

**Comment by phraktle** [comment]
Hah, that's a refreshingly simple bug :) I was actually going to check if perhaps it was constructed earlier in open, but dismissed that idea as "surely that would be too silly" and instead envisioned strange native stack corruptions 😵 

So shouldn't 30a93b48502cc2ce8befb73d36626ce156dbc512 be rolled back then as unnecessary, since MDB detects the error and it's reported properly now?

**Comment by benalexau** [comment]
https://github.com/lmdbjava/lmdbjava/commit/30a93b48502cc2ce8befb73d36626ce156dbc512 offers a few other benefits, like the `ThreadLocal` availability of the parent transaction (via `Env.txn()`) and `TutorialTest` demonstrating the use of a separate thread for the second transaction.

I'd be OK to remove the `ThreadHasTransactionException`, although I think this exception is much clearer for end users than receiving a `Txn#BadReaderLockException` (which is what you now get it if you comment out `Env`'s `throw new ThreadHasTransactionException()` line). Do you concur or think we're better off with the native exception?

**Comment by phraktle** [comment]
I think we're better off with directly matching what LMDB does without added overhead / complexity, unless it provides a significant reduction in complexity you need to understand. Since regardless of what you call the Exception, the library user would still need to understand thread constraints in LMDB and when/how to use MDB_NOTLS, I don't see this 30a93b4 worth it. I will add an idea for enhancement in #23 though.

**Comment by kamstrup** [comment]
Nice one @benalexau ! \o/

**Comment by krisskross** [comment]
Nice work!
