### ISSUE TITLE
Cannot open Dbi when Env is in read only mode.

### ISSUE THREAD

**Issue by mtanski** [lmdbjava/lmdbjava#8]
When the environment is create in read only mode a Dbi handle fails to create. This is because the openDbi method creates a WriteTxn. I'm not sure why that is the logic.

The problem is here:
```
  public Dbi<T> openDbi(final String name, final DbiFlags... flags) {
    try (Txn<T> txn = txnWrite()) {
      final Dbi<T> dbi = new Dbi<>(this, txn, name, flags);
      txn.commit();
      return dbi;
    } catch (ReadWriteRequiredException | CommittedException e) {
      throw new IllegalStateException(e); // cannot happen (Txn is try scoped)
    }
  }
```

There is an exception thrown as a result of this:
```
org.lmdbjava.LmdbNativeException$ConstantDerviedException: Platform constant error code: EACCES (13)
	at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:82)
	at org.lmdbjava.Txn.<init>(Txn.java:75)
	at org.lmdbjava.Env.txnWrite(Env.java:289)
	at org.lmdbjava.Env.openDbi(Env.java:213)
...
```

Code like this will not function (please ignore the Scala syntax)
```
  private[this] class LmdbEnv {
    val env: Env[ByteBuffer] = Env.create()
        .setMapSize(4, ByteUnit.GIBIBYTES)
        .setMaxDbs(1)
        .open(new File(conf.db_path), EnvFlags.MDB_RDONLY)
    val db = env.openDbi(conf.db_name)

    def close =
      env.close
  }
```

**Comment by mtanski** [comment]
Thanks for the quick fix.
